#!/bin/sh

set -e

php_enable() {
    # Don't enable PHP CGI by default
    return 1
}

if [ "$1" = "configure" ]; then
    update-alternatives \
	--install /usr/bin/php-cgi php-cgi /usr/bin/php-cgi8.2 82 \
	--slave /usr/share/man/man1/php-cgi.1.gz php-cgi.1.gz \
	/usr/share/man/man1/php-cgi8.2.1.gz

    update-alternatives \
	--install /usr/lib/cgi-bin/php php-cgi-bin /usr/lib/cgi-bin/php8.2 82
fi

CONFDIR=/etc/php/8.2/cgi/conf.d

if [ "$1" = "configure" ]; then
    phpini="/etc/php/8.2/cgi/php.ini"

    if [ "cgi" = "cli" ]; then
	ucf /usr/lib/php/8.2/php.ini-production.cgi $phpini
    else
	ucf /usr/lib/php/8.2/php.ini-production $phpini
    fi
    ucfr php8.2-cgi $phpini

    if [ -e /usr/lib/php/php-maintscript-helper ]; then
	. /usr/lib/php/php-maintscript-helper
	
	mods=$(phpquery -M -v 8.2)
	for mod in $mods; do
	    php_invoke enmod 8.2 cgi $mod
	done
    fi

    if [ -n "$2" ] && dpkg --compare-versions "$2" lt "7.0.3-2~"; then
	rm -f /etc/php/8.2/cgi/conf.d/20-opcache.ini;
    fi	    
fi

# Automatically added by dh_apache2/UNDECLARED
if php_enable; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in php8.2-cgi  ; do
			apache2_invoke enconf $conf  || exit 1
		done
	fi
fi
# End automatically added section


exit 0
